// Copyright 2021 Hayashi (@w_vwbw)
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H
#include "lib/add_keycodes.h"

enum layer_names {
  BASE = 0,
  LOWER,
  UPPER,
  LIGHT = 5,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [BASE] = LAYOUT(
    //RIGHT
            XXXXXXX, KC_EQL,KC_Y, KC_U, KC_I, KC_O,  KC_P,   KC_LBRC,KC_RBRC,KC_BSPC,
        XXXXXXX, KC_SPC,    KC_H, KC_J, KC_K, KC_L,  KC_SCLN,KC_QUOT,KC_ENT,XXXXXXX,
    LGUI_T(KC_SPC),MO(LOWER),KC_N, KC_M,KC_COMM,KC_DOT, KC_SLSH,KC_BSLS,KC_RSFT,LALT(KC_GRAVE),
    //LEFT
    KC_ESC, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_MINS,XXXXXXX, XXXXXXX,
                  XXXXXXX, CMD_CTL,KC_A, KC_S, KC_D, KC_F, KC_G,    KC_SPC,XXXXXXX, XXXXXXX,
                  XXXXXXX, KC_LSFT,KC_Z, KC_X, KC_C, KC_V, KC_B, MO(UPPER), LALT_T(KC_SPC),XXXXXXX
  ),
  [LOWER] = LAYOUT(
    //RIGHT
    XXXXXXX,         XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,LSFT(KC_9),LSFT(KC_0),XXXXXXX,
    XXXXXXX,     XXXXXXX,    KC_LEFT,KC_DOWN,  KC_UP,KC_RGHT,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,
    XXXXXXX,MO(LOWER),XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,KC_RSFT,XXXXXXX,
    //LEFT
    XXXXXXX,XXXXXXX,KC_1,KC_2,KC_3,KC_4,KC_5,KC_GRAVE,XXXXXXX, XXXXXXX,
          XXXXXXX,   XXXXXXX,KC_6,KC_7,KC_8,KC_9,KC_0,XXXXXXX,XXXXXXX, XXXXXXX,
          XXXXXXX,   XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX
  ),
  [UPPER] = LAYOUT(
    //RIGHT
      XXXXXXX,       XXXXXXX,KC_F1,KC_F2,KC_F3,KC_F4,KC_F5,KC_F6,XXXXXXX,KC_DEL,
       XXXXXXX,  XXXXXXX,    KC_F7,KC_F8,KC_F9,KC_F10,KC_F11,KC_F12,KC_UP,XXXXXXX,
    XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,KC_LEFT,KC_DOWN,KC_RGHT,
    //LEFT
    XXXXXXX,XXXXXXX,LSFT(KC_1),LSFT(KC_2),LSFT(KC_3),LSFT(KC_4),LSFT(KC_5),LSFT(KC_GRAVE),XXXXXXX, XXXXXXX,
         XXXXXXX,    XXXXXXX,LSFT(KC_6),LSFT(KC_7),LSFT(KC_8),LSFT(KC_9),LSFT(KC_0),XXXXXXX,XXXXXXX, XXXXXXX,
          XXXXXXX,   XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,MO(UPPER),XXXXXXX,XXXXXXX
  )
};
